### ISSUE TITLE
Failed to configure hierarchical states(Initial state's pseudostate kind must be INITIAL)

### ISSUE THREAD

**Issue by dantesun** [spring-projects/spring-statemachine#133]
I am using version 1.0.1.RELEASE. It is so wiered that the test case sometimes passed but sometimes failed. Is there something wrong with my configuration?

```Java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = StateMachineConfiguration.class)
public class StateMachineTest {
    @Autowired
    @Qualifier("stateMachineA")
    private StateMachine<States, Events> stateMachine;

    @Autowired
    private StateMachineTestService service;

    @Before
    public void setUp() {
    }

    @Test
    public void test_event() throws Exception {
        stateMachine.sendEvent(Events.EVENT1);
        stateMachine.sendEvent(Events.EVENT00);
        stateMachine.sendEvent(Events.EVENT11);
    }
}
```
```Java
@Configuration
@EnableStateMachine
public class StateMachineConfiguration {

    @Bean(initMethod = "start", name = "stateMachineA")
    StateMachine<States, Events> stateMachine() throws Exception {
        StateMachineTestService service = stateMachineTestService();
        StateMachineBuilder.Builder<States, Events> builder = StateMachineBuilder.builder();
        builder.configureStates().withStates().initial(States.INITIAL0).state(States.CHOICE).and().withStates().parent(
                States.CHOICE).initial(States.RESULT00).state(States.RESULT11).and().withStates().parent(States.CHOICE)
               .initial(States.RESULT11).state(States.RESULT12);

        StateMachineTransitionConfigurer<States, Events> transitionConfigurer = builder.configureTransitions();
        transitionConfigurer.withExternal().source(States.INITIAL0).target(States.CHOICE).event(Events.EVENT1).action(
                context -> System.out.println("INITIAL0 -> CHOICE"));
        transitionConfigurer.withExternal().source(States.CHOICE).target(States.RESULT00).event(Events.EVENT00).action(
                context -> System.out.println("CHOICE -> RESULT00"));
        transitionConfigurer.withExternal().source(States.CHOICE).target(States.RESULT11).event(Events.EVENT11).action(
                context -> System.out.println("CHOICE -> RESULT11"));
        builder.configureConfiguration().withConfiguration().taskExecutor(taskExecutor());
        return builder.build();
    }

    @Bean(name = StateMachineSystemConstants.TASK_EXECUTOR_BEAN_NAME)
    TaskExecutor taskExecutor() {
        return new SyncTaskExecutor();
    }
}
```

```Java
Caused by: java.lang.IllegalStateException: Initial state's pseudostate kind must be INITIAL
	at org.springframework.util.Assert.state(Assert.java:385)
	at org.springframework.statemachine.support.AbstractStateMachine.onInit(AbstractStateMachine.java:217)
	at org.springframework.statemachine.support.LifecycleObjectSupport.afterPropertiesSet(LifecycleObjectSupport.java:61)
	at org.springframework.statemachine.config.ObjectStateMachineFactory.buildStateMachineInternal(ObjectStateMachineFactory.java:79)
	at org.springframework.statemachine.config.AbstractStateMachineFactory.buildMachine(AbstractStateMachineFactory.java:547)
	at org.springframework.statemachine.config.AbstractStateMachineFactory.getStateMachine(AbstractStateMachineFactory.java:166)
	at org.springframework.statemachine.config.StateMachineBuilder$Builder.build(StateMachineBuilder.java:128)
	... 57 more
```

**Comment by dantesun** [comment]
Never mind, this is a ill-formed statemachine.
