### ISSUE TITLE
Got NullPointerException via State Machine Builder

### ISSUE THREAD

**Issue by yelong0201** [spring-projects/spring-statemachine#153]
I got a NullPointerException, seems like 'currentState' hadn't been initialized
```
java.lang.NullPointerException
	at org.springframework.statemachine.support.AbstractStateMachine.acceptEvent(AbstractStateMachine.java:591)
	at org.springframework.statemachine.support.AbstractStateMachine.sendEvent(AbstractStateMachine.java:202)
	at org.springframework.statemachine.support.AbstractStateMachine.sendEvent(AbstractStateMachine.java:212)
```
Did I miss something?
```
public class StateMachineFactory {

	public static final StateMachineFactory INSTANCE = new StateMachineFactory();
	
	private StateMachineFactory() { }
	
	private StateMachineActionFactory stateMachineActionFactory = StateMachineActionFactory.INSTANCE;
	
	public StateMachine<String, String> buildMachine() throws Exception {
	    Builder<String, String> builder = StateMachineBuilder.builder();
	    
	    builder.configureConfiguration()
	    	.withConfiguration()
	    		.listener(new StateMachineListenerAdapter<String, String>() {
	    			@Override
	    			public void stateChanged(State<String, String> from, State<String, String> to) {
	    				System.out.println("State change to " + to.getId());
	    			}
	    		});
	    
	    builder.configureStates()
	        .withStates()
	            .initial("SI")
	            .states(new HashSet<String>(Arrays.asList("SI","S1","S2","S3","S4","SF")))
	            .end("SF");
	    
	    builder.configureTransitions()
	    	.withExternal()
	    		.source("SI")
	    		.target("S1")
	    		.event("E1")
	    		.action(stateMachineActionFactory.action1());
	    return builder.build();
	}

}
```
```
StateMachine<String, String> stateMachine = StateMachineFactory.INSTANCE.buildMachine();
stateMachine.start();
stateMachine.sendEvent("E1");
```
autoStartup(true) doesn't work either

**Comment by jvalkeal** [comment]
You're missing a `taskExecutor` as it needs to be set manually with a builder. I probably need to add a default instance for it with a builder.
