### ISSUE TITLE
Exit action may get interrupted

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#233]
There is a SO question about exit action getting interrupted if its state also have a timer per `timerOnce`.
http://stackoverflow.com/questions/38016300/spring-state-machine-timeronce-transition-interrupting-exit-actions

I think a way it should work is that exit action(s) should be allowed to finish and I think we need to provide some sort of a hook for a timeout of execution of that exit action. If that exit action has a flaw and it runs indefinitely it may halt machine execution.

**Comment by jvalkeal** [comment]
Analysis shows dump
```
	at java.lang.Thread.sleep(Native Method)
	at org.springframework.statemachine.action.ActionAndTimerTests$TestExitAction.execute(ActionAndTimerTests.java:154)
	at org.springframework.statemachine.state.AbstractState.executeAction(AbstractState.java:366)
	at org.springframework.statemachine.state.ObjectState.exit(ObjectState.java:149)
	at org.springframework.statemachine.support.AbstractStateMachine.exitFromState(AbstractStateMachine.java:1084)
	at org.springframework.statemachine.support.AbstractStateMachine.exitCurrentState(AbstractStateMachine.java:1033)
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentState(AbstractStateMachine.java:912)
	at org.springframework.statemachine.support.AbstractStateMachine.switchToState(AbstractStateMachine.java:793)
	at org.springframework.statemachine.support.AbstractStateMachine.access$3(AbstractStateMachine.java:768)
	at org.springframework.statemachine.support.AbstractStateMachine$2.transit(AbstractStateMachine.java:308)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleTriggerTrans(DefaultStateMachineExecutor.java:242)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.processTriggerQueue(DefaultStateMachineExecutor.java:385)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$1(DefaultStateMachineExecutor.java:323)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:271)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.scheduleEventQueueProcessing(DefaultStateMachineExecutor.java:290)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$5(DefaultStateMachineExecutor.java:256)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:284)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.scheduleEventQueueProcessing(DefaultStateMachineExecutor.java:290)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$5(DefaultStateMachineExecutor.java:256)
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$2.triggered(DefaultStateMachineExecutor.java:452)
	at org.springframework.statemachine.trigger.CompositeTriggerListener.triggered(CompositeTriggerListener.java:34)
	at org.springframework.statemachine.trigger.TimerTrigger.notifyTriggered(TimerTrigger.java:115)
	at org.springframework.statemachine.trigger.TimerTrigger.access$0(TimerTrigger.java:114)
	at org.springframework.statemachine.trigger.TimerTrigger$1.run(TimerTrigger.java:109)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
we get recursive calls to scheduleEventQueueProcessing and existing countermeasures don't prevent things to go south.
