### ISSUE TITLE
remove dependency on spring-core org/springframework/util/Assert

### ISSUE THREAD

**Issue by n0mer** [spring-projects/spring-statemachine#244]
Hi,

trying to use spring-statemachine in non-spring environment using builder:

```java
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/springframework/util/Assert;
                                                                                     at org.springframework.statemachine.config.common.annotation.AbstractConfiguredAnnotationBuilder.<init>(AbstractConfiguredAnnotationBuilder.java:91)
                                                                                     at org.springframework.statemachine.config.builders.StateMachineModelBuilder.<init>(StateMachineModelBuilder.java:54)
                                                                                     at org.springframework.statemachine.config.StateMachineBuilder$BuilderStateMachineConfigurerAdapter.getStateMachineModelBuilder(StateMachineBuilder.java:211)
                                                                                     at org.springframework.statemachine.config.StateMachineBuilder$BuilderStateMachineConfigurerAdapter.<init>(StateMachineBuilder.java:165)
                                                                                     at org.springframework.statemachine.config.StateMachineBuilder$Builder.<init>(StateMachineBuilder.java:76)
                                                                                     at org.springframework.statemachine.config.StateMachineBuilder.builder(StateMachineBuilder.java:57)
```

method in question: 
```java
org.springframework.statemachine.config.common.annotation.AbstractConfiguredAnnotationBuilder#AbstractConfiguredAnnotationBuilder(org.springframework.statemachine.config.common.annotation.ObjectPostProcessor<java.lang.Object>, boolean)
```

code
```java
	/**
	 * Instantiates a new annotation builder.
	 *
	 * @param objectPostProcessor the object post processor
	 * @param allowConfigurersOfSameType the allow configurers of same type
	 */
	protected AbstractConfiguredAnnotationBuilder(ObjectPostProcessor<Object> objectPostProcessor, boolean allowConfigurersOfSameType) {
		Assert.notNull(objectPostProcessor, "objectPostProcessor cannot be null");
		this.objectPostProcessor = objectPostProcessor;
		this.allowConfigurersOfSameType = allowConfigurersOfSameType;
	}
```

Class org/springframework/util/Assert belongs to spring-core, which is transitively included via `spring-messaging` and `spring-tx`. If you need only statemachine itself - you've got no luck:

```groovy
    compile("org.springframework.statemachine:spring-statemachine-core:1.1.0.RELEASE") {
        exclude group: 'org.springframework', module: 'spring-messaging'
        exclude group: 'org.springframework', module: 'spring-tx'
    }
```

**Comment by jvalkeal** [comment]
Well Spring Statemachine is a Spring project and depends on a Spring Framework. You can't remove these core dependencies.

**Comment by n0mer** [comment]
Speaking of assert itself - it is possible to copy-paste sources into the project, just to have Assert working

![image](https://cloud.githubusercontent.com/assets/1862997/17889982/4d35f72e-6933-11e6-95f7-5c29d777c948.png)

But this is, obviously, weird way to work-around this issue.

**Comment by n0mer** [comment]
I do math project on non-enterprise environment, interested in state machine from math perspective. spring-statemachine is most advanced state machine written in java so far, and i'm trying to use it in non-standard way without spring application context.

Came up with this set of dependencies:

```groovy
    testCompile("org.springframework:spring-core:4.2.4.RELEASE")
    testCompile("org.springframework:spring-context:4.2.4.RELEASE")
    testCompile("org.springframework:spring-tx:4.2.4.RELEASE")
    testCompile("org.springframework.statemachine:spring-statemachine-core:1.1.0.RELEASE") {
```

for this piece of code from reference docs:

```java
    static StateMachine<String, String> buildMachine() throws Exception {
        StateMachineBuilder.Builder<String, String> builder = StateMachineBuilder.builder();
        builder.configureStates()
                .withStates()
                .initial("S1")
                .end("SF")
                .states(new HashSet<>(Arrays.asList("S1","S2","S3","S4")));
        builder.configureTransitions()
                .withExternal()
                .source("SI").target("S1").event("E1")
                .and()
                .withExternal()
                .source("S1").target("S2").event("E2");
        return builder.build();
    }
```

**Comment by jvalkeal** [comment]
Right, sorry I thought you meant without spring core whatsoever. Manual builders were added so that that you can use machines without Application Context.
