### ISSUE TITLE
Tests are fragile

### ISSUE THREAD

**Issue by xylifyx** [spring-projects/spring-statemachine#36]
Once and awhile the tests fail. Saw a failed test in CdPlayerTests.testPlayLcdTimeChanges and this one at
demo.cdplayer.CdPlayerTests.testPlayPause(CdPlayerTests.java:171)

Using latches to test asynchronous stuff is difficult

java.lang.AssertionError: 
Expected: is <2>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at demo.cdplayer.CdPlayerTests.testPlayPause(CdPlayerTests.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by jvalkeal** [comment]
Yes I'll try to come up with a better way to test these. I saw same trouble with CI builds so really need to get it fixed.

**Comment by jvalkeal** [comment]
Tests has been stable for few days now and every attempt to get a failure hasn't provided a failed build. Marking fixed, re-open if related tests starts to fail.

**Comment by jvalkeal** [comment]
Re-open due to new CI failure
```
java.lang.AssertionError: java.lang.AssertionError: 
Expected: is <1>
     but: was <0>
java.lang.AssertionError: 
Expected: is <1>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.springframework.statemachine.StateMachineTests.testTimerTransition(StateMachineTests.java:102)
```

**Comment by jvalkeal** [comment]
Re-open again due to CI failure:

```
java.lang.AssertionError: java.lang.AssertionError: 
Expected: is <1>
     but: was <0>
java.lang.AssertionError: 
Expected: is <1>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at demo.cdplayer.CdPlayerTests.testPlayLcdTimeChanges(CdPlayerTests.java:131)
```

**Comment by jvalkeal** [comment]
Marking this fixed now. Getting ready for next milestone so further CI failures will be handled in a separate tickets.
