### ISSUE TITLE
ConcurrentModificationException when running statemachine with the heavy load

### ISSUE THREAD

**Issue by Ewg-sha** [spring-projects/spring-statemachine#445]
Hi,

I am observing following exception from statemachine, can someone help to investigate it?

2017-11-27T19:41:27,455 [ERROR] (RARS-FSM-EXEC-7) [] UncaughtException: Uncaught exception in thread "RARS-FSM-EXEC-7"
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_141]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_141]
        at org.springframework.statemachine.state.AbstractState.cancelStateActions(AbstractState.java:363) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.state.AbstractState.exit(AbstractState.java:199) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.state.ObjectState.exit(ObjectState.java:144) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine.exitFromState(AbstractStateMachine.java:1143) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine.exitCurrentState(AbstractStateMachine.java:1088) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine.setCurrentStateInternal(AbstractStateMachine.java:967) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine.setCurrentState(AbstractStateMachine.java:949) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine.switchToState(AbstractStateMachine.java:841) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine.access$400(AbstractStateMachine.java:77) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.AbstractStateMachine$2.transit(AbstractStateMachine.java:298) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleInitialTrans(DefaultStateMachineExecutor.java:263) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.DefaultStateMachineExecutor.processTriggerQueue(DefaultStateMachineExecutor.java:344) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$100(DefaultStateMachineExecutor.java:61) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:287) ~[spring-statemachine-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

Background: we are creating statemachines using builder. we create one instance of statemachines for each incoming request. We process 4000 requests per second in the load test to get above exception. We observer 1 such exception approximately per minute. We re-use statemachine by placing them back to FSM pool after request is processed (in "end" state). Before fsm instance is re-used it is reset by below code:
`
reusableFSM.stop();
reusableFSM.getState().exit(null); // since it leaks events
rarsFsmHandler.removeMetricListener(reusableFSM); // since it leaks listeners (new attached to every FSM)
reusableFSM.getExtendedState().getVariables().clear();
reusableFSM.getStateMachineAccessor()
        .doWithAllRegions(access -> {
            access.resetStateMachine(
                    new DefaultStateMachineContext(AuthorityManagerStates.ST_FSM_START, null, null, null));
        });
`

**Comment by jvalkeal** [comment]
This might be caused by
```
reusableFSM.stop();
reusableFSM.getState().exit(null); // since it leaks events
```
as both should result call to `AbstractState.cancelStateActions()`. What's the issue when you added comment `since it leaks events`.

**Comment by jvalkeal** [comment]
Or maybe not, as that exception is most likely when machine starts. Would you be able to share your tests as that would help me to diagnose this?

**Comment by Ewg-sha** [comment]
Thank you for looking into the problem Janne. I cannot share the tests, since this is load test in production, but I can share as much information as possible.
The exception is not coming from the above code as it is inside of try-catch, it also cannot come from fsm.start() for the same reason. The exception is coming from some task added to ThreadPoolExecutor, and it can be added on start I suppose, or it can be added in event processing loop.
I forgot to mention another piece of code:
```
            Field tmpField1 = null, tmpField2 = null;
            try {
                tmpField1 = AbstractStateMachine.class.getDeclaredField("stateMachineExecutor");
                tmpField1.setAccessible(true);
            } catch(NoSuchFieldException e) {
                log.error("RARS_REFLECTION_FAILURE: Cannot get access to internals of AbstractStateMachine.", e);
            }
            try {
                tmpField2 = DefaultStateMachineExecutor.class.getDeclaredField("eventQueue");
                tmpField2.setAccessible(true);
            } catch(NoSuchFieldException e) {
                log.error("RARS_REFLECTION_FAILURE: Cannot get access to internals of DefaultStateMachineExecutor.", e);
            }
            fsmExecutorField = tmpField1;
            msgQueueField = tmpField2;

...
    private void executeEventLoop(StateContext<AuthorityManagerStates, AuthorityManagerEvents> context) {
        StateMachine<AuthorityManagerStates, AuthorityManagerEvents> fsm = context.getStateMachine();
        StateMachineExecutor<AuthorityManagerStates, AuthorityManagerEvents> fsmExecutor;
        try {
            fsmExecutor = (StateMachineExecutor)fsmExecutorField.get(fsm);
            boolean skipExecutiong = false;
            if(msgQueueField != null) {
                Queue<Message> msgQueue = (Queue)msgQueueField.get(fsmExecutor);
                skipExecutiong = msgQueue.isEmpty();
            }
            if( !skipExecutiong ) {
                log.info("forcing execution of FSM's event loop (factory): " + fsm.getUuid());
                fsmExecutor.execute();
                RarsRequestContext requestContext = fsmHandler.getRarsRequestContext(context);
                requestContext.getMetricsCollector().addCount(MetricNames.METRIC_RARS_FSM_EVENT_LOOP_COUNT.getMetricName(), 1);
            }
        } catch (Exception e) {
            log.warn("Exception caught while attempting to execute FSM's event loop (through reflection)", e);
        }
    }

....
        if(fsmExecutorField != null && msgQueueField != null) {
            builder.configureTransitions()
                .withInternal()
                    .source(ST_20C_GET_SOURCE_RECEIVED)
                    .timerOnce(10)
                    .action(this::executeEventLoop)
                    .and()
                .withInternal()
                    .source(ST_20C_GET_DEST_RECEIVED)
                    .timerOnce(10)
                    .action(this::executeEventLoop)
                    .and();
        }

```
The reason for above injection is that FSM may stuck and never process the second event sent to FSM from outside of the FSM (we receive message from the network and it takes us to _RECEIVED state inside of a fork, we had to receive response from 2 systems in order to proceed to join, and in 1-2 FSMs out of 10000, the second event is never processed by FSM, however 10ms might be too tight and I can try to increase this time to decrease chance of double event loop execution).

For your other question about the reusableFSM.getState().exit(null); // since it leaks events
We return FSM into pool in the last state of the FSM:
```
.state(ST_FSM_COMPLETE, context -> onComplete(context))
...
    private void onComplete(StateContext<AuthorityManagerStates, AuthorityManagerEvents> context) {
        fsmPool.returnFSM(context.getStateMachine());
    }
```
when we are doing so, the state is never exited and we leak action stored inside of "cancellableActions":
...
public abstract class AbstractState<S, E> extends LifecycleObjectSupport implements State<S, E> 
private final List<ScheduledFuture<?>> cancellableActions = new ArrayList<>();
...

**Comment by jvalkeal** [comment]
Right ok. This awfully sounds like one test I already have which it extremely difficult to get to fail and with this test event is also not processed while it's queued into executor. I think what you wrote actually gives me some more tools or ideas what happens. Hopefully your issue is a same. I'll try to use some more time debugging this.
