### ISSUE TITLE
SOE with persistence and orthogonal states

### ISSUE THREAD

**Issue by cornelcreanga** [spring-projects/spring-statemachine#615]
Hi,

Version: 2.0.3.RELEASE
Test project https://github.com/cornelcreanga/statemachine-fork
Configure the database(*), run the Application.java  and notice the error:

```
Exception in thread "stateMachineTaskExecutor-3" java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.size(ConcurrentHashMap.java:910)
	at org.springframework.statemachine.support.ObservableMap.size(ObservableMap.java:64)
	at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1082)
	at org.springframework.statemachine.support.ObservableMap.putAll(ObservableMap.java:112)
	at org.springframework.statemachine.persist.AbstractPersistingStateMachineInterceptor.buildStateMachineContext(AbstractPersistingStateMachineInterceptor.java:127)
	at org.springframework.statemachine.persist.AbstractPersistingStateMachineInterceptor.buildStateMachineContext(AbstractPersistingStateMachineInterceptor.java:137)
```

Thanks.

(*) 
You need postgresql to run the sample - if you want to use a docker image you can use the following docker compose file. Otherwise you will need to modify application.properties accordingly.

```
version: '2'
services:
db:
image: postgres:alpine
ports:
- "6432:5432"
restart: always
environment:
POSTGRES_DB: test
POSTGRES_USER: validation_user
POSTGRES_PASSWORD: validation_pass
```

@razmanolescu

**Comment by cornelcreanga** [comment]
hi, any update on this?

**Comment by jvalkeal** [comment]
I think I saw this as well with a work I've been doing with #605. Hopefully it will get fixed with it.

**Comment by cornelcreanga** [comment]
tkx. kindly let me know when you'll push the changes so I can test/move to the next evaluation scenario.
