### ISSUE TITLE
Upgrade to Kryo 4

### ISSUE THREAD

**Issue by don-vip** [spring-projects/spring-statemachine#625]
Can you please update to Kryo 4.x ?

It contains support of Java 8 date/times (https://github.com/EsotericSoftware/kryo/issues/358)
With the current version (3) we get the following error:

```
	  Caused by: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.time.LocalDateTime
Serialization trace:
creationDate (com.xxx.MyObject)
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1272)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1078)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1087)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:570)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:546)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:759)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
	at org.springframework.statemachine.kryo.StateMachineContextSerializer.read(StateMachineContextSerializer.java:57)
	at org.springframework.statemachine.kryo.StateMachineContextSerializer.read(StateMachineContextSerializer.java:38)
```

**Comment by jvalkeal** [comment]
Yes, might be a good idea. I was just wondering if you have tried to use kryo4 with statemachine by changing deps?

Note to myself, ping spring-integration guys as even they are still on v3 for kryo support.

**Comment by don-vip** [comment]
Hi,
Yes I tried to update the Maven dependency and found no issue so far. But we're still in the process of implementing persistence in our project, so my tests are not really relevant. Another feedback would be more useful than mine.

**Comment by jvalkeal** [comment]
Tests didn't bark and looked some sample which were ok. Let's do it for 2.1.x. Looks like SI is also replacing kryo version in 5.2.x.
