### ISSUE TITLE
Random failures in Tests

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#76]
Some very random failures with 

TasksTests:
```
java.lang.AssertionError: 
Expected: iterable containing [<ERROR>, <MANUAL>]
     but: No item matched: <MANUAL>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at demo.tasks.TasksTests.testFailManualFix(TasksTests.java:111)
```

ZookeeperStateMachineEnsembleTests testEventsOverflow
```
java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.springframework.statemachine.zookeeper.ZookeeperStateMachineEnsembleTests.testEventsOverflow(ZookeeperStateMachineEnsembleTests.java:563)
```

```
java.lang.AssertionError: java.lang.AssertionError: Key testVariable doesn't exist in extended state variables
Expected: is <true>
     but: was <false>
java.lang.AssertionError: Key testVariable doesn't exist in extended state variables
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.springframework.statemachine.test.StateMachineTestPlan.test(StateMachineTestPlan.java:229)
	at org.springframework.statemachine.zookeeper.ZookeeperStateMachineTests.testExtendedStateVariables2(ZookeeperStateMachineTests.java:381)

```

**Comment by jvalkeal** [comment]
marking this fixed after a lot of succeed testing.
