### ISSUE TITLE
Cannot reuse a sub-machine containing a choice and multiple exit points

### ISSUE THREAD

**Issue by don-vip** [spring-projects/spring-statemachine#801]
We face the following error when building the attached state machine:

```
java.lang.IllegalArgumentException: Initial state must be set
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.springframework.statemachine.support.AbstractStateMachine.onInit(AbstractStateMachine.java:237)
	at org.springframework.statemachine.support.LifecycleObjectSupport.afterPropertiesSet(LifecycleObjectSupport.java:67)
	at org.springframework.statemachine.config.AbstractStateMachineFactory.getStateMachine(AbstractStateMachineFactory.java:332)
	at org.springframework.statemachine.config.AbstractStateMachineFactory.getStateMachine(AbstractStateMachineFactory.java:148)
	at ItemStateMachineUmlValidatorTest.getStateMachine(ItemStateMachineUmlValidatorTest.java:50)
	at ItemStateMachineUmlValidatorTest.checkStateMachineCorectness(ItemStateMachineUmlValidatorTest.java:57)
...
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

We pinned down the issue to reusing multiple times a submachine containing at least a choice and several exit points. Here are the diagrams of a minimalist reproducible example:

Level 1 machine:
![ItemStateMachine_Diagram](https://user-images.githubusercontent.com/596867/62546431-bf2a3c00-b863-11e9-8f0c-933fb6be97b7.PNG)

Level 2 submachines:
![CASE1_Diagram](https://user-images.githubusercontent.com/596867/62546428-be91a580-b863-11e9-970b-092cfb66ac9b.PNG)
![CASE2_Diagram](https://user-images.githubusercontent.com/596867/62546430-be91a580-b863-11e9-8f75-0ed8730c0b9f.PNG)

Level 3 submachine reused two times in level 2 machines:
![SUB_Diagram](https://user-images.githubusercontent.com/596867/62546432-bf2a3c00-b863-11e9-8833-e55021c84da2.PNG)

To reproduce, you can load the attached example and run the JUnit test `ItemStateMachineUmlValidatorTest.checkStateMachineCorectness`.
[SubMachine_Reuse.zip](https://github.com/spring-projects/spring-statemachine/files/3472642/SubMachine_Reuse.zip)

During our investigation, we noticed that:
- using the submachine only one times works
- reusing multiple times a submachine that contains a choice and a single exit point works
- reusing multiple times a submachine that contains no choice and multiple exit points works
- reusing multiple times a submachine that contains a choice and multiple exit points does not work

**Comment by jvalkeal** [comment]
We don't currently support using same states in a different submachines. Essentially you end up with same state in two different places. It's definitely something what would be nice to get working as reusing bits would simplify things.

**Comment by don-vip** [comment]
OK thank you, we were not aware of this limitation.
