### ISSUE TITLE
JPA tests fails with h2 1.4.200

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#817]
Eventually with some tests we end up to:
```
09:42:21.311 [main] DEBUG org.hibernate.tool.schema.internal.SchemaDropperImpl$DelayedDropActionImpl - Error performing delayed DROP command [drop table action if exists]
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop table action if exists" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot drop "ACTION" because "FK_STATE_INITIAL_ACTION, FK_STATE_ENTRY_ACTIONS_A, FK_STATE_EXIT_ACTIONS_A, FK_STATE_STATE_ACTIONS_A, FK_TRANSITION_ACTIONS_A" depends on it; SQL statement:
drop table action if exists [90107-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
```
This is something to do with hibernate and h2. Looks like until things work with h2 1.4.200 we need to go back to 1.4.199.

**Comment by jvalkeal** [comment]
Looks like actual issue is in https://hibernate.atlassian.net/projects/HHH/issues/HHH-13711
