### ISSUE TITLE
NullPointerException when persisting orthogonal states

### ISSUE THREAD

**Issue by mladendinev** [spring-projects/spring-statemachine#936]
This is my SMM configuration which I have : 
  ```
@Override
    public void configure(StateMachineStateConfigurer<States, Events> states)
            throws Exception {

        states
                .withStates()
                .initial(States.CREATED)
                .state(States.STARTED
                .join(States.ALL_PROCESSES_COMPLETED)
                .state(States.PROCESSES)
                .and()
                .withStates()
                    .parent(States.PROCESSES)
                    .initial(States.CHECK_1)
                    .state(States.CHECK_1)
                    .end(States.CHECK_1_END)
                    .and()
                .withStates()
                    .parent(States.PROCESSES)
                    .initial(States.CHECK_2)
                    .state(States.CHECK_2)
                    .end(States.CHECK_2_END)
                    .and()
                .withStates()
                    .parent(States.PROCESSES)
                    .initial(States.CHECK_3)
                    .state(States.CHECK_3)
                    .end(States.CHECK_3_END);;
    }

    @Override
    public void configure(
            StateMachineTransitionConfigurer<States, Events> transitions)
            throws Exception {

        transitions
                .withJoin()
                    .source(States.CHECK_1_END)
                    .source(States.CHECK_2_END)
                    .source(States.CHECK_3_END)
                    .target(States.ALL_PROCESSES_COMPLETED)
                .and()
                    .withExternal()
                    .source(States.CREATED).target(States.STARTED).event(Events.STARTED)
                .and()
                    .withExternal()
                    .source(States.STARTED).target(States.PROCESSES)
                .and()
                    .withExternal()
                    .source(States.CHECK_1).target(States.CHECK_1_END).event(Events.CHECK_1_EVENT)
                .and()
                    .withExternal()
                    .source(States.CHECK_2).target(States.CHECK_2_END).event(Events.CHECK_2_EVENT)
                .and()
                    .withExternal()
                    .source(States.CHECK_3).target(States.CHECK_3_END).event(Events.CHECK_3_EVENT);;
    }
```

when I try to persist it after post state change 

```
    @Override
    public void preStateChange(State<States, Events> state, Message<Events> message,
                                Transition<States, Events> transition, StateMachine<States, Events> stateMachine,
                                StateMachine<States, Events> rootStateMachine) {

        try {
            persister.persist(rootStateMachine, stateMachine.getId());
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        super.preStateChange(state, message, transition, stateMachine, rootStateMachine);
    }
```
I get null pointer exception

```
java.lang.NullPointerException
	at org.springframework.statemachine.persist.AbstractStateMachinePersister.buildStateMachineContext(AbstractStateMachinePersister.java:90)
	at org.springframework.statemachine.persist.AbstractStateMachinePersister.buildStateMachineContext(AbstractStateMachinePersister.java:98)
	at org.springframework.statemachine.persist.AbstractStateMachinePersister.persist(AbstractStateMachinePersister.java:65)
	at 
```

**Comment by mladendinev** [comment]
I checked the source code and I found out that when the SMM reaches the PROCESSES state it runs the 3 regions in parallel, but only the first one has a current state which I do not understand why. The _buildStateMachineContext_  method recursively goes through the orthogonal states and fails on the second region - in this case CHECK_2.

**Comment by mladendinev** [comment]
The problem is reproducible in version 3.0.0 as well. Any idea when that could be resolved?
